server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wsl2.sbx0.cn:3306/todo
    username: root
    password: justfordev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      hbm2ddl:
        schema-generation:
          script:
            append: false
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./todo-service/src/main/resources/db/auto/generate.sql
logging:
  file:
    name: ./logs/current.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/current-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: false
      max-file-size: 1MB
      total-size-cap: 1GB
      max-history: 30
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: debug
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
weixin:
  app-id: 1
  app-secret: 2
  auth:
    token: 3
chatgpt:
  api-key: 4