spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wsl2.sbx0.cn:3306/todo
    username: root
    password: justfordev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  file:
    name: ./logs/current.log
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/current-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: false
      max-file-size: 1MB
      total-size-cap: 1GB
      max-history: 30
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace
