version: '3.7'
services:
  todo-service:
    image: todo-service:latest
    restart: always
    ports:
      - "1112:9999"
    volumes:
      - ./logs:/logs
    networks:
      - default_network
    environment:
      - TZ=Asia/Shanghai
networks:
  default_network:
    name: default_network
    external: true
