ALTER TABLE tasks
    ADD user_id BIGINT UNSIGNED DEFAULT 1 NOT NULL COMMENT 'user id';
ALTER TABLE categories
    ADD user_id BIGINT UNSIGNED DEFAULT 1 NULL COMMENT 'user id';
ALTER TABLE asset_records
    ADD user_id BIGINT UNSIGNED DEFAULT 1 NOT NULL COMMENT 'user id';
ALTER TABLE asset_types
    ADD user_id BIGINT UNSIGNED DEFAULT 1 NOT NULL COMMENT 'user id';