export const POST = "POST";
export const GET = "GET";
export const ApiPrefix = process.env.NODE_ENV === 'development' ? "http://localhost:3000" : "https://todo.sbx0.cn";
export const API = "/api";
export const TaskPaging = API + "/task/paging";
export const TaskSortedPaging = API + "/task/sortedPaging";
export const TaskComplete = API + "/task/complete";
export const CategoryPaging = API + "/category/paging";
export const TaskStatistics = API + "/task/statistics";
export const AssetTypePaging = API + "/asset/type/paging";
export const RecentRecordTimeList = API + "/asset/record/getRecentRecordTimeList";
export const AssetRecords = API + "/asset/record/getRecords";
