export const POST = "POST";
export const GET = "GET";
export const ApiPrefix = "http://";
export const API = "/api";
export const TaskPaging = API + "/task/paging";
export const CategoryPaging = API + "/category/paging";
export const TaskStatistics = API + "/task/statistics";
export const AssetRecordPaging = API + "/asset/record/paging";
export const AssetTypePaging = API + "/asset/type/paging";
