version: '3.7'
services:
  todo-web:
    image: todo-web:latest
    ports:
      - "3000:3000"
    volumes:
      - /etc/timezone:/etc/timezone
    networks:
      - default-network
networks:
  default-network:
    name: default-network
    external: true