version: '3.7'
services:
  todo-web:
    image: todo-web:latest
    ports:
      - "3000:3000"
    volumes:
      - /etc/timezone:/etc/timezone
    networks:
      - default_network
networks:
  default_network:
    name: default_network
    external: true