import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";
import {listApi, saveApi} from "../apis/taskApi";

export default function Home() {
  const [list, setList] = useState([]);
  const [newTask, setNewTask] = useState(null);

  useEffect(() => {
    listApi().then((res) => {
      setList(res.data)
    })
  }, []);

  const saveNewTask = () => {
    if (newTask == null) {
      return;
    }
    if (newTask === '') {
      return;
    }
    if (newTask.trim() === '') {
      return;
    }
    saveApi({
      taskName: newTask
    }).then(() => {
      listApi().then(r => setList(r.data));
    })
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>Next Todo App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main className={styles.main}>
          <div className={styles.contentArea}>
            {list.map((one) =>
                <div key={'taskInfo_' + one.id}>{one.taskName}</div>)
            }
          </div>
          <div className={styles.operationArea}>
            <label htmlFor='taskInput'
                   className={styles.taskLabel}>
              New Task
            </label>
            <input type='text'
                   id='taskInput'
                   placeholder='Input New Task'
                   onChange={(event) => setNewTask(event.target.value)}
                   className={styles.taskInput}/>
            <button onClick={saveNewTask}
                    type='button'
                    className={styles.taskButton}>
              Save New Task
            </button>
          </div>
        </main>

        <footer className={styles.footer}>

        </footer>
      </div>
  )
}
