### get token
POST win.sbx0.cn:9999/token
Authorization: Basic user password

### get token
GET win.sbx0.cn:9999/
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlciIsImV4cCI6MTY3ODgyMjQ2NywiaWF0IjoxNjc4Nzg2NDY3LCJzY29wZSI6ImFwcCJ9.YweqN9FDuJU0mryaKXhG49v11SlHd_Xwh6uaw-5yuVDvnnzSl1eZtk-2qzxaf-yyOViCh1sjEm0ZktGJMmcXwNVNmZBRj36ZbRHtIEE7m8CwEmtrMitdPtDNRJVey73p6ZkOxRQ4OMegmU4AskAuqJ3h-J26NtXMqX4T_Wt4R9XaPVWX9zHSDH0aUFccLZJT76I1CIM_TNx0JIu2pN4AFAwwrlYdnI_r4zdR8JTLEuJ2ofKPs_5RQ2LNk9GqG_QkHaolZ_RzY9UXCCLlr8hclz6jiAwohgwJtXOHKS9brD4EKQ4wrqcSppWq0BykiOOLxe5kNeodLHpf-Or0XnYdtg

### get token
POST win.sbx0.cn:3000/api/task/paging
Content-Type: application/json

{
  "page": 1,
  "pageSize": 10
}
