### login
POST win.sbx0.cn:9999/user/client/login
Authorization: Basic admin@sbx0.cn admin@sbx0.cn

### register
POST win.sbx0.cn:9999/user/client/register
Content-Type: application/json

{
  "email": "admin@sbx0.cn1",
  "password": "admin@sbx0.cn1"
}

### asset type paging
POST win.sbx0.cn:9999/asset/type/paging
Content-Type: application/json

{
  "page": 1,
  "pageSize": 10
}
