name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        working-directory: ./todo-service
        run: chmod +x ./gradlew
      - name: Build with Gradle
        id: gradle
        working-directory: ./todo-service
        run: ./gradlew build
      - name: Upload Test Report to Server
        if: github.ref == 'refs/heads/main'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: '${{ secrets.SERVER }}'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          local_path: './todo-service/build/reports/jacoco/test/html/*'
          remote_path: '/home/ubuntu/todo/code-coverage'
          args: '-o ConnectTimeout=5'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: npm install
        working-directory: ./todo-web
        run: npm install
      - name: npm run test
        working-directory: ./todo-web
        run: npm run test
      - name: npm run build
        working-directory: ./todo-web
        run: npm run build
